const fs=require('fs'),vm=require('vm'),assert=require('assert');
function run(stored,blocked=false,reduced=true){
let handler;const values=new Map(stored===null?[]:[['brady-theme',stored]]);const label={hidden:true};const select={closest:()=>label,addEventListener:(_,f)=>handler=f};
const classes=new Set(); let motionClick, preferenceChange; const art={classList:{toggle:(k,on)=>{const enabled=on===undefined?!classes.has(k):on; enabled?classes.add(k):classes.delete(k);return enabled}}}; const motionButton={hidden:true,addEventListener:(_,f)=>motionClick=f};const preference={matches:reduced,addEventListener:(_,f)=>preferenceChange=f};
const document={documentElement:{dataset:{}},getElementById:id=>id==='theme'?select:{},querySelectorAll:()=>[],querySelector:s=>s==='.art-wrap'?art:motionButton};const localStorage={getItem:k=>{if(blocked)throw Error();return values.get(k)},setItem:(k,v)=>{if(blocked)throw Error();values.set(k,v)},removeItem:k=>{if(blocked)throw Error();values.delete(k)}};
const context={document,localStorage,matchMedia:()=>preference,Date,window:{}};vm.createContext(context);
for(const f of ['theme.js','script.js'])vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../docs/')+f,'utf8'),context);
return {classes,motionButton,motionClick,setReduced:v=>{preference.matches=v;preferenceChange()},document,select,label,values,change:v=>{select.value=v;handler()}};
}
for(const initial of [null,'system','invalid','light','dark']){const s=run(initial);assert.equal(s.select.value,['light','dark'].includes(initial)?initial:'system');assert.equal(s.label.hidden,false);s.change('dark');assert.equal(s.document.documentElement.dataset.theme,'dark');assert.equal(s.values.get('brady-theme'),'dark');s.change('light');assert.equal(s.document.documentElement.dataset.theme,'light');s.change('system');assert.equal(s.document.documentElement.dataset.theme,undefined);assert.equal(s.values.has('brady-theme'),false)}
const s=run(null,true);s.change('dark');assert.equal(s.document.documentElement.dataset.theme,'dark');s.change('system');assert.equal(s.document.documentElement.dataset.theme,undefined);
console.log('Theme checks passed: system default, valid/invalid saved overrides, changes, reset, unavailable storage, reduced motion, no observer.');

const motion=run(null,false,false);assert(motion.classes.has('motion-enabled'));assert.equal(motion.motionButton.hidden,false);motion.motionClick();assert(motion.classes.has('motion-paused'));assert.equal(motion.motionButton.textContent,'Resume animation');motion.motionClick();assert(!motion.classes.has('motion-paused'));motion.setReduced(true);assert(!motion.classes.has('motion-enabled'));assert(motion.motionButton.hidden);console.log('Motion checks passed: looping enabled, pause/resume, live reduced-motion changes.');
